### ISSUE TITLE
No IP

### ISSUE THREAD

**Issue by tommedIO** [arteck/iobroker.judoisoft#1]
Hi Arthur,

vielen Danke für das Erstellen des Adapters. Auf diesen hab ich lange gewartet. Super, dass du die Basis erstellt hast. Beim Testen tritt bei mir leider folgender Error auf:

"(11145) No one IP configured". Die IP ist in der Instanz hinterlegt. Die IP der Enthärtungsanlage beginnt mit 172.20.2.XXX. D.h. das ist nicht der Standardadressbereich der vielen Fritzboxen. Der IoBroker läuft aber auf jeden Fall im gleichen Subnet wie die Enthärtungsanlage.

**Comment by mirage-111** [comment]
![5B4D1B96-0CB8-43C4-882D-228DAFAB03C5](https://user-images.githubusercontent.com/55852325/103441308-4a705280-4c4d-11eb-99fa-bb9e563cb66e.jpeg)

same issue, here a screenshot of the log

**Comment by arteck** [comment]
der adapter ist für die judo isoft plus geschrieben... obs mit einer anderen Anlage auch läfut müsst ihr mir sagen...

was passiert auf port 8124.. da muss ein JSON ausgegeben werden... sonst läuft der Adapter nicht mit euer Anlage

**Comment by tommedIO** [comment]
> der adapter ist für die judo isoft plus geschrieben... obs mit einer anderen Anlage auch läfut müsst ihr mir sagen...
> 
> was passiert auf port 8124.. da muss ein JSON ausgegeben werden... sonst läuft der Adapter nicht mit euer Anlage

Ah, da liegt wohl der Fehler begraben. Ich habe eine i.Soft safe. Schade, dass es dafür noch nichts passendes gibt. Ist dafür eine Erweiterung des Adapters geplant?

**Comment by ronnythomas** [comment]
> > der adapter ist für die judo isoft plus geschrieben... obs mit einer anderen Anlage auch läfut müsst ihr mir sagen...
> > was passiert auf port 8124.. da muss ein JSON ausgegeben werden... sonst läuft der Adapter nicht mit euer Anlage
> 
> Ah, da liegt wohl der Fehler begraben. Ich habe eine i.Soft safe. Schade, dass es dafür noch nichts passendes gibt. Ist dafür eine Erweiterung des Adapters geplant?

Kommt bei dir was auf dem Port?

**Comment by tommedIO** [comment]
> > > der adapter ist für die judo isoft plus geschrieben... obs mit einer anderen Anlage auch läfut müsst ihr mir sagen...
> > > was passiert auf port 8124.. da muss ein JSON ausgegeben werden... sonst läuft der Adapter nicht mit euer Anlage
> > 
> > 
> > Ah, da liegt wohl der Fehler begraben. Ich habe eine i.Soft safe. Schade, dass es dafür noch nichts passendes gibt. Ist dafür eine Erweiterung des Adapters geplant?
> 
> Kommt bei dir was auf dem Port?

Beim Aufruf der IP-Adresse:8124 im Browser kommt leider nichts. Oder wie sollte ich prüfen, ob etwas kommt? Sorry für die recht einfachen Fragen.

**Comment by joker17177** [comment]
Hallo!

Bei mir kommt beim Aufruf von "https://IPAdresse:8124" folgendes:

{"null":"","status":"error","data":"no token"}

**Comment by arteck** [comment]
@tommedIO dann sollte es auch gehen.. und du trägst NUR die ip ein

**Comment by joker17177** [comment]
@arteck Kannst du mir auch noch einen Tip geben? Komme einfach nicht weiter.

**Comment by tommedIO** [comment]
> @tommedIO dann sollte es auch gehen.. und du trägst NUR die ip ein..und iobroker kann auf diese auch zugreifen

Hat sich die Antwort auf meinen Post bezogen? Bei mir kommt nämlich leider nichts beim Aufruf der IPAdresse:8124. 

@joker17177 Bei dir kommt ja etwas. Welche Judo Anlage hast du?

**Comment by joker17177** [comment]
Hast du es auch mit HTPPS versucht? 
Ich bin im Besitz von 2 ISoft Plus Anlagen...

**Comment by tommedIO** [comment]
> Hast du es auch mit HTPPS versucht?
> Ich bin im Besitz von 2 ISoft Plus Anlagen...

Ja, habe ich auch versucht. Ich habe "leider nur" eine i.soft safe.

**Comment by joker17177** [comment]
Ich spiele mit dem Gedanken, die Anlage auf Werkseinstellungen zurückzusetzen und beim Einrichten (wie in der Anleitung zur Anlage beschrieben) die Datenschutzbestimmungen abzulehnen...

**Comment by arteck** [comment]
@joker17177 was den für ein Tipp .. wozu ?? ip eintragen daten eintragen adapter starten.. fettisch

**Comment by joker17177** [comment]
@arteck

Ich habe zwei ISoft Plus Anlagen. Eine ist per WLAN die Andere per LAN mittels fester IP Adressen in mein Netzwerk eingebunden. Bei beiden Anlage kommt nach dem start des Adapters folgendes:

judoisoft.0 | 2021-01-03 14:24:06.315 | error | (914) No one IP configured
judoisoft.0 | 2021-01-03 14:24:06.280 | info | (914) starting. Version 0.0.1 in /opt/iobroker/node_modules/iobroker.judoisoft, node: v12.20.0, js-controller: 3.1.6
host.IOBroker | 2021-01-03 14:24:05.048 | info | instance system.adapter.judoisoft.0 started with pid 914
host.IOBroker | 2021-01-03 14:24:05.003 | info | "system.adapter.judoisoft.0" enabled

**Comment by joker17177** [comment]
OK, habs gefunden....


judoisoft.0 | 2021-01-03 14:37:31.003 | debug | (1092) WaterStop true
judoisoft.0 | 2021-01-03 14:37:31.002 | debug | (1092) stateID judoisoft.0.WaterStop changed: true (ack = false)
judoisoft.0 | 2021-01-03 14:37:30.967 | debug | (1092) get Information
judoisoft.0 | 2021-01-03 14:37:30.958 | debug | (1092) position 10 {"group":"waterstop","command":"valve","msgnumber":"4","":"","token":"undefined","status":"error","data":"not logged in"}
judoisoft.0 | 2021-01-03 14:37:30.958 | debug | (1092) position 9 {"group":"consumption","command":"water yearly","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
judoisoft.0 | 2021-01-03 14:37:30.957 | debug | (1092) position 8 {"group":"consumption","command":"water total","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
judoisoft.0 | 2021-01-03 14:37:30.957 | debug | (1092) position 7 {"group":"waterstop","command":"quantity","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
judoisoft.0 | 2021-01-03 14:37:30.957 | debug | (1092) position 6 {"group":"waterstop","command":"flow rate","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
judoisoft.0 | 2021-01-03 14:37:30.956 | debug | (1092) position 5 {"group":"info","command":"natural hardness","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
judoisoft.0 | 2021-01-03 14:37:30.956 | debug | (1092) position 4 {"group":"settings","command":"residual hardness","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
judoisoft.0 | 2021-01-03 14:37:30.955 | debug | (1092) position 3 {"group":"consumption","command":"water average","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
judoisoft.0 | 2021-01-03 14:37:30.955 | debug | (1092) position 2 {"group":"consumption","command":"salt quantity","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
judoisoft.0 | 2021-01-03 14:37:30.955 | debug | (1092) position 1 {"group":"consumption","command":"salt range","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
judoisoft.0 | 2021-01-03 14:37:30.953 | debug | (1092) position 0 {"group":"consumption","command":"water current","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
judoisoft.0 | 2021-01-03 14:37:29.397 | debug | (1092) get Information
judoisoft.0 | 2021-01-03 14:37:29.394 | debug | (1092) get Information Static 3 {"group":"contract","command":"service date","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
judoisoft.0 | 2021-01-03 14:37:29.394 | debug | (1092) get Information Static 2 {"group":"contract","command":"init date","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
judoisoft.0 | 2021-01-03 14:37:29.394 | debug | (1092) get Information Static 1 {"group":"version","command":"hardware version","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
judoisoft.0 | 2021-01-03 14:37:29.393 | debug | (1092) get Information Static 0 {"group":"version","command":"software version","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
judoisoft.0 | 2021-01-03 14:37:27.489 | debug | (1092) get Information Static
judoisoft.0 | 2021-01-03 14:37:27.487 | debug | (1092) connect Result: {"group":"register","command":"connect","msgnumber":"1","token":"undefined","parameter":"undefined","serial number":"undefined","status":"error","data":"not logged in"}
judoisoft.0 | 2021-01-03 14:37:27.435 | debug | (1092) getSerialnumber : {"group":"register","command":"show","msgnumber":"2","token":"undefined","status":"error","data":"not logged in"}
judoisoft.0 | 2021-01-03 14:37:27.207 | debug | (1092) getToken: {"group":"register","command":"login","msgnumber":"1","name":"login","user":"joker17177","password":"*","role":"customer","status":"error","data":"login failed"}
judoisoft.0 | 2021-01-03 14:37:13.793 | debug | (1092) getURL: https://192.168.0.41:8124/?group=register&command=login&msgnumber=1&name=login&user=***&password=***&role=customer
judoisoft.0 | 2021-01-03 14:37:13.779 | debug | (1092) create state
judoisoft.0 | 2021-01-03 14:37:13.777 | error | (1092) No one IP configured
judoisoft.0 | 2021-01-03 14:37:13.776 | debug | (1092) serial undefined
judoisoft.0 | 2021-01-03 14:37:13.746 | info | (1092) starting. Version 0.0.1 in /opt/iobroker/node_modules/iobroker.judoisoft, node: v12.20.0, js-controller: 3.1.6
judoisoft.0 | 2021-01-03 14:37:13.372 | debug | (1092) statesDB connected
judoisoft.0 | 2021-01-03 14:37:13.371 | debug | (1092) States connected to redis: 127.0.0.1:9000
judoisoft.0 | 2021-01-03 14:37:13.362 | debug | (1092) States create System PubSub Client
judoisoft.0 | 2021-01-03 14:37:13.358 | debug | (1092) States create User PubSub Client
judoisoft.0 | 2021-01-03 14:37:13.350 | debug | (1092) Redis States: Use Redis connection: 127.0.0.1:9000
judoisoft.0 | 2021-01-03 14:37:13.347 | debug | (1092) objectDB connected
judoisoft.0 | 2021-01-03 14:37:13.340 | debug | (1092) Objects connected to redis: 127.0.0.1:9001
judoisoft.0 | 2021-01-03 14:37:13.327 | debug | (1092) Objects client initialize lua scripts
judoisoft.0 | 2021-01-03 14:37:13.325 | debug | (1092) Objects create User PubSub Client
judoisoft.0 | 2021-01-03 14:37:13.323 | debug | (1092) Objects create System PubSub Client
judoisoft.0 | 2021-01-03 14:37:13.313 | debug | (1092) Objects client ready ... initialize now
judoisoft.0 | 2021-01-03 14:37:13.272 | debug | (1092) Redis Objects: Use Redis connection: 127.0.0.1:9001
host.IOBroker | 2021-01-03 14:37:12.389 | info | instance system.adapter.judoisoft.0 started with pid 1092
host.IOBroker | 2021-01-03 14:37:12.337 | info | "system.adapter.judoisoft.0" enabled

**Comment by ronnythomas** [comment]
> 
> 
> OK, habs gefunden....
> 
> judoisoft.0 | 2021-01-03 14:37:31.003 | debug | (1092) WaterStop true
> judoisoft.0 | 2021-01-03 14:37:31.002 | debug | (1092) stateID judoisoft.0.WaterStop changed: true (ack = false)
> judoisoft.0 | 2021-01-03 14:37:30.967 | debug | (1092) get Information
> judoisoft.0 | 2021-01-03 14:37:30.958 | debug | (1092) position 10 {"group":"waterstop","command":"valve","msgnumber":"4","":"","token":"undefined","status":"error","data":"not logged in"}
> judoisoft.0 | 2021-01-03 14:37:30.958 | debug | (1092) position 9 {"group":"consumption","command":"water yearly","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
> judoisoft.0 | 2021-01-03 14:37:30.957 | debug | (1092) position 8 {"group":"consumption","command":"water total","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
> judoisoft.0 | 2021-01-03 14:37:30.957 | debug | (1092) position 7 {"group":"waterstop","command":"quantity","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
> judoisoft.0 | 2021-01-03 14:37:30.957 | debug | (1092) position 6 {"group":"waterstop","command":"flow rate","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
> judoisoft.0 | 2021-01-03 14:37:30.956 | debug | (1092) position 5 {"group":"info","command":"natural hardness","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
> judoisoft.0 | 2021-01-03 14:37:30.956 | debug | (1092) position 4 {"group":"settings","command":"residual hardness","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
> judoisoft.0 | 2021-01-03 14:37:30.955 | debug | (1092) position 3 {"group":"consumption","command":"water average","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
> judoisoft.0 | 2021-01-03 14:37:30.955 | debug | (1092) position 2 {"group":"consumption","command":"salt quantity","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
> judoisoft.0 | 2021-01-03 14:37:30.955 | debug | (1092) position 1 {"group":"consumption","command":"salt range","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
> judoisoft.0 | 2021-01-03 14:37:30.953 | debug | (1092) position 0 {"group":"consumption","command":"water current","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
> judoisoft.0 | 2021-01-03 14:37:29.397 | debug | (1092) get Information
> judoisoft.0 | 2021-01-03 14:37:29.394 | debug | (1092) get Information Static 3 {"group":"contract","command":"service date","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
> judoisoft.0 | 2021-01-03 14:37:29.394 | debug | (1092) get Information Static 2 {"group":"contract","command":"init date","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
> judoisoft.0 | 2021-01-03 14:37:29.394 | debug | (1092) get Information Static 1 {"group":"version","command":"hardware version","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
> judoisoft.0 | 2021-01-03 14:37:29.393 | debug | (1092) get Information Static 0 {"group":"version","command":"software version","msgnumber":"1","token":"undefined","status":"error","data":"not logged in"}
> judoisoft.0 | 2021-01-03 14:37:27.489 | debug | (1092) get Information Static
> judoisoft.0 | 2021-01-03 14:37:27.487 | debug | (1092) connect Result: {"group":"register","command":"connect","msgnumber":"1","token":"undefined","parameter":"undefined","serial number":"undefined","status":"error","data":"not logged in"}
> judoisoft.0 | 2021-01-03 14:37:27.435 | debug | (1092) getSerialnumber : {"group":"register","command":"show","msgnumber":"2","token":"undefined","status":"error","data":"not logged in"}
> judoisoft.0 | 2021-01-03 14:37:27.207 | debug | (1092) getToken: {"group":"register","command":"login","msgnumber":"1","name":"login","user":"**_","password":"_","role":"customer","status":"error","data":"login failed"}
> judoisoft.0 | 2021-01-03 14:37:13.793 | debug | (1092) getURL: https://192.168.0.41:8124/?group=register&command=login&msgnumber=1&name=login&user=***&password=***&role=customer
> judoisoft.0 | 2021-01-03 14:37:13.779 | debug | (1092) create state
> judoisoft.0 | 2021-01-03 14:37:13.777 | error | (1092) No one IP configured
> judoisoft.0 | 2021-01-03 14:37:13.776 | debug | (1092) serial undefined
> judoisoft.0 | 2021-01-03 14:37:13.746 | info | (1092) starting. Version 0.0.1 in /opt/iobroker/node_modules/iobroker.judoisoft, node: v12.20.0, js-controller: 3.1.6
> judoisoft.0 | 2021-01-03 14:37:13.372 | debug | (1092) statesDB connected
> judoisoft.0 | 2021-01-03 14:37:13.371 | debug | (1092) States connected to redis: 127.0.0.1:9000
> judoisoft.0 | 2021-01-03 14:37:13.362 | debug | (1092) States create System PubSub Client
> judoisoft.0 | 2021-01-03 14:37:13.358 | debug | (1092) States create User PubSub Client
> judoisoft.0 | 2021-01-03 14:37:13.350 | debug | (1092) Redis States: Use Redis connection: 127.0.0.1:9000
> judoisoft.0 | 2021-01-03 14:37:13.347 | debug | (1092) objectDB connected
> judoisoft.0 | 2021-01-03 14:37:13.340 | debug | (1092) Objects connected to redis: 127.0.0.1:9001
> judoisoft.0 | 2021-01-03 14:37:13.327 | debug | (1092) Objects client initialize lua scripts
> judoisoft.0 | 2021-01-03 14:37:13.325 | debug | (1092) Objects create User PubSub Client
> judoisoft.0 | 2021-01-03 14:37:13.323 | debug | (1092) Objects create System PubSub Client
> judoisoft.0 | 2021-01-03 14:37:13.313 | debug | (1092) Objects client ready ... initialize now
> judoisoft.0 | 2021-01-03 14:37:13.272 | debug | (1092) Redis Objects: Use Redis connection: 127.0.0.1:9001
> host.IOBroker | 2021-01-03 14:37:12.389 | info | instance system.adapter.judoisoft.0 started with pid 1092
> host.IOBroker | 2021-01-03 14:37:12.337 | info | "system.adapter.judoisoft.0" enabled

Entwerden du hast den Benutzernamen oder das Passwort falsch. Bei dem Benutzernamen auf groß/kleinschreibung achten.
 
Adapter klappt 1A.
...schnell mal noch ne kleine Vis dazu gebaut.
![Unbenannt](https://user-images.githubusercontent.com/41967174/103482711-a4eee780-4de2-11eb-8bb8-f21f75f69b28.JPG)

**Comment by joker17177** [comment]
Ok. Die Verbindung steht jetzt.
Jetzt wollte ich für meine zweite Anlage eine zweite Instanz hinzufügen und bekam leider folgende Meldung:
"Fertig mit Fehler: this adapter does not allow multiple instances on one host"
Muß ich jetzt einen zweiten host anlegen, oder gibt es da eine andere Möglichkeit?

**Comment by arteck** [comment]
0.0.4 ist da

**Comment by joker17177** [comment]
@arteck
Jetzt funzt es. Habe auch bereits 2 Instanzen zu laufen. Vielen Dank, für diesen Adapter und deine Mühen!!!
