### ISSUE TITLE
Unregelmäßige Fehlermeldung Judo iSoft Safe

### ISSUE THREAD

**Issue by Claus1985** [arteck/ioBroker.judoisoft#10]
Hi Artec,

vielen Dank für Deine Mühe und den genialen Adapter!
Habe darüber meine isoft Safe angebunden. Funktioniert 
Soweit auch gut, bekomme nur alle 1-2 Tage folgenden Error:

`judoisoft.0 | 2021-04-10 03:00:15.892 | error | --- property 'socket' closes the circle
-- | -- | -- | --
judoisoft.0 | 2021-04-10 03:00:15.892 | error | \| property '_httpMessage' -> object with constructor 'ClientRequest'
judoisoft.0 | 2021-04-10 03:00:15.892 | error | --> starting at object with constructor 'TLSSocket'
judoisoft.0 | 2021-04-10 03:00:15.892 | error | (21720) Converting circular structure to JSON
judoisoft.0 | 2021-04-10 03:00:15.892 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
judoisoft.0 | 2021-04-10 03:00:15.892 | error | at runMicrotasks (<anonymous>)
judoisoft.0 | 2021-04-10 03:00:15.892 | error | at judoisoftControll.getInfosCloud (/opt/iobroker/node_modules/iobroker.judoisoft/main.js:279:58)
judoisoft.0 | 2021-04-10 03:00:15.892 | error | at JSON.stringify (<anonymous>)
judoisoft.0 | 2021-04-10 03:00:15.892 | error | --- property 'socket' closes the circle
judoisoft.0 | 2021-04-10 03:00:15.892 | error | \| property '_httpMessage' -> object with constructor 'ClientRequest'
judoisoft.0 | 2021-04-10 03:00:15.892 | error | --> starting at object with constructor 'TLSSocket'
judoisoft.0 | 2021-04-10 03:00:15.892 | error | (21720) TypeError: Converting circular structure to JSON
judoisoft.0 | 2021-04-10 03:00:15.890 | error | --- property 'socket' closes the circle
judoisoft.0 | 2021-04-10 03:00:15.890 | error | \| property '_httpMessage' -> object with constructor 'ClientRequest'
judoisoft.0 | 2021-04-10 03:00:15.890 | error | --> starting at object with constructor 'TLSSocket'
judoisoft.0 | 2021-04-10 03:00:15.890 | error | (21720) unhandled promise rejection: Converting circular structure to JSON
judoisoft.0 | 2021-04-10 03:00:15.863 | error | (21720) Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().`

Kannst Du mir hier weiterhelfen?

Danke und Gruß,

Claus

**Comment by arteck** [comment]
installiere den adapter neu.. ich habe gerade anpassungen gemacht

**Comment by Claus1985** [comment]
Top, danke für die Info! Von welchem Pfad? Experimentell oder einfach den normalen GitHub Master? Recht drüber installieren?

**Comment by Claus1985** [comment]
@arteck Version 1.08 funtkioniert bei mir nicht, bekomme folgende Meldung im log:

`
judoisoft.0 | 2021-04-17 14:00:16.655 | error | (19536) getInfosCloud ERROR {}
-- | -- | -- | --
judoisoft.0 | 2021-04-17 14:00:16.367 | info | (19536) reconnect 1618660816367
judoisoft.0 | 2021-04-17 14:00:15.733 | info | (19536) starting. Version 1.0.8 in /opt/iobroker/node_modules/iobroker.judoisoft, node: v12.22.1, js-controller: 3.2.16

`

**Comment by arteck** [comment]
adapter auf debug stellen und log posten

**Comment by arteck** [comment]
nach der SerialNumber sollte die 

SoftwareVersion kommen .. da gibts ein problem bei dir

**Comment by Claus1985** [comment]
@arteck wie kann ich das Lösen / woran kann das liegen?

**Comment by Brandy-f1** [comment]
@Claus1985 Hat sich dein Problem schon gelöst?
Hast die Aktuelle Version installiert?

**Comment by Claus1985** [comment]
> @Claus1985 Hat sich dein Problem schon gelöst?
> Hast die Aktuelle Version installiert?

Die letzte Version hat leider nicht funktioniert und ich konnte bisher auch keine Lösung finden.

**Comment by Brandy-f1** [comment]
@Claus1985  Hast du mal den Adapter deinstalliert und den Objektbaum des judosoft gelöscht? 

Danach Neustart und nochmals installieren.

**Comment by Claus1985** [comment]
Das hat funktioniert, danke für den Tip! Bekomme nun nur noch zwei Meldungen im Log aber das kann ich selbst anpassen:
`State value to set for "judoisoft.0.Maintenance" has to be type "number" but received type "string"
State value to set for "judoisoft.0.ServiceDays" has to be type "number" but received type "string"`
