### ISSUE TITLE
Adapter Stoppt

### ISSUE THREAD

**Issue by Brandy-f1** [arteck/ioBroker.judoisoft#14]
Mir ist aufgefallen, daß der Adapter in unregelmässigen Abständen immer wieder gestoppt wird.
Ich hab das LOG von mir als ZIP angehängt.
Habs als CSV Formatiert und nach Judoisoft gefiltert.
Wenn ich das richtig gesehen hab, ist der Stop um 17:16 passiert. um ca. 18:15 hab ichs mitbekommen und den Adapter wieder gestartet.
[LOG_20210607.zip](https://github.com/arteck/iobroker.judoisoft/files/6610670/LOG_20210607.zip)

Wenn noch weitere Infos benötigt werden, bitte einfach melden.

Gruß

Brandy

**Comment by arteck** [comment]
kann sein dass du da die Internetverbindung verloren hast ?

**Comment by Brandy-f1** [comment]
Die Zwangstrennung meines DSL ist erst später als  3 Uhr, ich glaub so um 5 Uhr. 
Dass der Adapter stoppt, ist auch tagsüber passiert bei laufendem DSL.
Ich werd die Sache mal weiter noch beobachten, aber aus meiner Sicht stoppte der Adapter auch bei laufendem DSL.
Wenn Du noch Infos zur Eingrenzung brauchst, sag Bescheid.

**Comment by Brandy-f1** [comment]
Ich hab zum Stop des Adapters zwei Szenarien eingrenzen können:
1. DSL fällt aus -> Adapter stoppt und startet nicht mehr selbständig (aktuell nicht der Fall)
2. Die Gegenseite von JUDO ist offline (heute aktuell passiert) -> Adapter stoppt und startet nicht mehr selbständig.

Anbei noch das LOG von heute.

[iobroker.2021-07-29.log](https://github.com/arteck/iobroker.judoisoft/files/6900350/iobroker.2021-07-29.log)

Ich konnte den Adapter anschliessend nach einigen Versuchen manuell starten, aber die Gegenseite ist dezeit noch offline (lt. APP)

**Comment by Brandy-f1** [comment]
Heute ist der Adapter durch einen DSL-Ausfall bei Gewitter wieder gestoppt. Leider ist nach DSL Wiederkehr der Adapte nicht wieder angelaufen, musste von Hand gestartet werden.  Hier noch der Screenshot der Absturzmeldung und meine LOG von Heute.
Der DSL Ausfall war laut Router Protokoll 19:08 - 19:13.
Für ne Hilfe wär ich dankbar.
Die Judoseite hab ich gecheckt, die ist online.

[iobroker.2021-08-15.zip](https://github.com/arteck/iobroker.judoisoft/files/6988587/iobroker.2021-08-15.zip)
![Screenshot 2021-08-15 192612](https://user-images.githubusercontent.com/60137562/129487713-0011c021-a83c-4cbe-867f-38d85b6b70ae.jpg)

VG 

Brandy

**Comment by arteck** [comment]
der adapter wechselt aber den Status.. diesen kannst du mit einem Script/Blockly abfangen und den adapter neu starten..
das kriege ich im Adapter nicht abgefangen da ich nicht zur Abfrage nicht weiss was nicht läuft..
besser mit einem Script abfangen

**Comment by Brandy-f1** [comment]
Vielen Dank für die Info!!!
Wenn ich eine script / blockly hab, werd ich die Lösung noch einstellen.

**Comment by Brandy-f1** [comment]
Mittlerweile hab ich mir auf Basis folgendem Links eine Blockly/VIS Lösung zum manuellen Restart des Adapters gebaut:
https://www.smarthome-tricks.de/software-iobroker/iobroker-adapter-neustart-ueber-vis/

![Judo_Adapter_Restart](https://user-images.githubusercontent.com/60137562/141742620-1057c02f-413f-4d4f-a0ea-b8acc319f616.jpg)

Manuell hab ichs deshalb, damit ich über VIS mitbekommen, wann der Adapter stoppt und ich gezielt darauf reagiere.
