### ISSUE TITLE
No value water.Yearly / cloud access

### ISSUE THREAD

**Issue by CG28** [arteck/ioBroker.judoisoft#17]
Hallo zusammen,

erst mal vielen Dank für den Adapter, viele Werte werden bereits ausgelesen und können über meine VIS angezeigt werden. 

Ich habe eine i-soft safe mit Cloudzugang. In der App werden auch alle Verbrauchsdaten korrekt angezeigt.

Leider erhalte ich über den Adapter z.B. keine Werte für die Monatsverbräuche:

![grafik](https://user-images.githubusercontent.com/63516077/135722158-67b3e280-d343-4759-9a03-7de9aa43b0d4.png)

Adapter läuft aber ohne Probleme und ein Großteil der Daten ist auch verfügbar:

![grafik](https://user-images.githubusercontent.com/63516077/135722196-7f7d2bdf-cfe8-4bb1-8bc7-180a1fe5e7c0.png)

Aber leider nicht alle:
![grafik](https://user-images.githubusercontent.com/63516077/135722516-db9df085-6ba1-42db-8187-efff78602a6b.png)

Muss ich evtl. die Datentypen anpassen (Zahl/Info etc.)?

![grafik](https://user-images.githubusercontent.com/63516077/135722262-571c8b5d-1b91-497e-97d3-ae276a34387c.png)

Danke für eure Hilfe.

**Comment by Brandy-f1** [comment]
Hallo CG28,
Hab mir gerade die Objekte in meinem Adapter angesehen.
Den Ordnerjudosoft.0.wateryearly hab ich in meiner Struktur nicht drin.
Ich glaub den gabs in einer früheren Version mal. Arteck hatte ja die Daten die ausgelesen werden auf das notwendigste begrenzt, ich glaub die Statistikwerte sind nicht mehr enthalten. 
Mein Objektbaum entsprcht deinem 2. Bild.
Meine Version: 1.0.10

Ich verwende den Adapter haupsächlich zum steueren der Restwasserhärte und des Waterstops. Hab mir dazu die quasi die betriebsarten der Judo App in VIS und Blockly "nachgebaut".
