### ISSUE TITLE
Meldung aufgrund falscher Datentypen

### ISSUE THREAD

**Issue by Claus1985** [arteck/ioBroker.judoisoft#19]
Hallo Zusammen,

nachdem der Adapter inzwischen einwandfrei funktioniert habe ich allerdings noch ein Problem.
Ich bekomme immer wieder folgende Infomeldung:

`State value to set for "judoisoft.0.Maintenance" has to be type "number" but received type "string"
State value to set for "judoisoft.0.ServiceDays" has to be type "number" but received type "string"`

Wenn ich die Datentypen manuell umstelle kommt nichts mehr allerdings stellt sich das von alleine wieder auf den falschen Typ zurück. Wäre es möglich das direkt im Adapter anzupassen oder gibt es eine Möglichkeit für mich das dauerhaft zu ändern?

Danke und Gruß,

Claus

**Comment by arteck** [comment]
installier nochmal.. bitte
