### ISSUE TITLE
Webinterface (isoft safe)

### ISSUE THREAD

**Issue by tommedIO** [arteck/iobroker.judoisoft#2]
Hallo Arthur,

nach ein bisschen Recherche konnte ich herausfinden, dass die I.Soft Safe Geräte über die Website ähnlich angesprochen werden können, wie die Plus Geräte direkt im Netzwerk. So wird es für das FHEM-Plugin beschrieben: https://wiki.fhem.de/wiki/JUDO_iSoft_Plus#JUDO_iSoft_Safe

Der Login findet dort über folgende URL statt:
https://www.myjudo.eu/interface/?group=register&command=login&name=login&user=MeinUser&password=MD5VomPasswort&nohash=Service&role=customer
Das Passwort muss als MD5 eingegeben werden. 

Ich habe den Link mit meinen Login-Daten mal testet. Das hatte auch so funktioniert. Als Antwort erhalte ich den Token zurück:

{"status":"ok","token":"8cbe63209XXXXXXXXXXXXX","role":"customer","notifications":{"email":"0","sms":"0","push":"1"},"startpage":null,"data":[],"servicenumber":""}

Nach dem Login erhält man dann unter: 
https://www.myjudo.eu/interface/?token=8cbe63209XXXXXXXXXXXXX&group=register&command=get%20device%20data
JSON ausgegeben.

Könntest du diese Schnittstelle in deinen Adapter integrieren?

**Comment by mirage-111** [comment]
Super Info tommedIO !  
@arteck das wär echt super wenn du den Adapter dahingehend erweitern könntest.
Lass mich wissen falls du nen Versuchskaninchen benötigst.

**Comment by arteck** [comment]
dann schaumal.. in einstellungen musst du das häckchen setzten für cloud

**Comment by Brandy-f1** [comment]
Hallo Arthur,

Danke für Deine Mühen zur Adapterentwicklung!

Ich habe auch eine isoft safe wie oben von tommedIO beschrieben, leider bekomme ich über den Cloud Login keine vernünftigen Daten und der Adapter steht auf Gelb.

Bitte um Hilfe was ich hier evtl. falsch mache. Ich habe die Inststanz gelöscht und und neu angelegt.
Nach einem restart erhalte ich folgenden LOG Eintrag:


judoisoft.0 | 2021-02-01 16:09:02.907 | error | (24029) getInfos ERROR""
-- | -- | -- | --
judoisoft.0 | 2021-02-01 16:09:01.700 | info | (24029) starting. Version 1.0.2 in /opt/iobroker/node_modules/iobroker.judoisoft, node: v12.20.0, js-controller: 3.2.12

Wie kann ich den Adapter auf debug stellen um evtl weitere Infos zu erhalten.
Merci schon mal für deine Hilfe!

**Comment by tommedIO** [comment]
Hallo Arthur,

vielen Dank für die Integration. Ich habe heute die neue Version getestet. Leider erhalte ich den gleichen Fehler wie Brandy. Der Fehler erscheint bei korrekten Einwahldaten. Bei falschen Einwahldaten geht der Adapter auf grün, aber die Objekte werden nicht gefüllt.

Bei korrekten Einwahldaten geht der Adapter auf gelb mit dem von Brandy beschriebenen Fehler. Es werden jedoch zwei Objekte gefüllt: 
- SerialNumber: Er holt sich die passende Serialnummer. Diese stimmt mit der Serialnummer meiner Anlage überein
- token: Er holt sich einen passenden Token. Rufe ich manuell über die zuvor schon mal genannte URL: https://www.myjudo.eu/interface/?token=xxxxx&group=register&command=get%20device%20data die Schnittstelle auf, erhalte ich eine JSON-Rückmeldung. D.h. der Login klappt und die Erzeugung des Token klappt.
- Die anderen Objekte bleiben leider leer. 

Kann man dir sonst noch mit Input weiterhelfen?

Vielen Dank und viele Grüße

**Comment by Brandy-f1** [comment]
Danke für die genaue Fehlerbeschreibung tommedIO.
Genau das gleiche Verhalten ist bei mir aufgetaucht.

Den Adapter auf Debug zu stellen, hab ich mitlerweile hinbekommen.

Wenn ich auch noch irgendwie zur Verbesserung beitragen kann, bitte Bescheid sagen.

Eine Anlage zum Test ist bei mir ja vorhanden.

VG

Brandy

**Comment by arteck** [comment]
ich lese die seite aus die die Anlage lifert.. dann wird diese anders in der Cloud aussehen..
ich müsste mir das live anschauen.. um festzustellen b das so ist ..
kennt ihr unseren discord kanal ? dann bitte mich dort anschreiben

**Comment by mirage-111** [comment]
@arteck 
Hab das gleiche Problem wie Brandy-f1 und tommediO. (GetInfoError) und keine Daten werden übertragen.
Discord Kanal ? Kannst du nen Link posten.
Ich würde mich auch für ne Live Demo zur Verfügung stellen.
VG

**Comment by arteck** [comment]
@tommedIO hast du die gnaze liste für die abfragen ausser die get device data ??

**Comment by tommedIO** [comment]
@arteck Leider nein. Ich hatte auch mal versucht noch mehr Infos zu finden. Habe aber leider auch keine Ahnung wo ich dazu noch mehr finden kann. 

Welchen Discord meinst du?

**Comment by arteck** [comment]
iobroker discord...

**Comment by Brandy-f1** [comment]
Servus Zusammen,

Ich bin die letzten Tage über einen Alexa Skill für die Judoanlagen gestolpert. Hab mal daraufhin eine Anfrage bei Judo gestartet ob es denn nicht möglich wäre für den IO-Broker weitere Infos zu bekommen. Ne Antwort hab ich leider noch nicht bekommen.

Würde es weiterhelfen, mit dem Skill zu versuchen an Komandos zu kommen?
Ich hab da leider keinerlei Ahnung ;-(

**Comment by kramerlein** [comment]
Hallo,

zunächst wollte ich mich für die bisherige Arbeit bedanken. Weiterhin wollte ich mich kurz erkundigen, ob der Adapter dahingehend noch erweitert werden kann, oder ob sonst eine Möglichkeit besteht die I-soft safe mit IOBroker zu verbinden?

Vielen Dank

**Comment by arteck** [comment]
> 
> 
> Hallo,
> 
> zunächst wollte ich mich für die bisherige Arbeit bedanken. Weiterhin wollte ich mich kurz erkundigen, ob der Adapter dahingehend noch erweitert werden kann, oder ob sonst eine Möglichkeit besteht die I-soft safe mit IOBroker zu verbinden?
> 
> Vielen Dank

du hast dir das hier aber schon durchgelesen und das Problem erkannt ??

**Comment by thstickel** [comment]
Hallo Arthur,

ich würde gern versuchen ein wenig zu unterstützen. Ich habe eine Judo Safe zum testen und könnte ggf. ein wenig weiterhelfen.

Zunächst sollte der Login wie bereits oben beschrieben halt in zwei Schritten erfolgen:

1. `https://www.myjudo.eu/interface/?group=register&command=login&name=login&user=`*Benutzername*`&password=`*PasswortalsMD5Hash*`&nohash=Service&role=customer`   

   Erzeugt einen Token für weiter HTTP-Requests

   ​	--> Ergebnis: 
   `{"status":"ok","token":"XXXXXXXXXXXXXXXXXXXXXXXXXXXX","role":"customer","notifications":{"email":"1","sms":"0","push":"1"},"startpage":null,"data":[],"servicenumber":""}`

2. `https://www.myjudo.eu/interface/?token=`*TOKEN_VON_OBEN*`&group=register&command=get%20device%20data`

   ​	--> Ergebnis 
   `{"data":[{"serialnumber":"6827XXXXX5eb","installation_date":"","status":"online","sv":"1.11","hv":"1.0","data":[{"da":"0x1","dt":"0x33","sv":"2.9h","hv":"5.10","data":{"1":{"data":"680902","st":"OK","er":""},"2":{"data":"0A05","st":"OK","er":""},"3":{"data":"22290300","st":"OK","er":""},"5":{"data":"000A6200","st":"OK","er":""},"6":{"data":"5FBC8CBF","st":"OK","er":""},"7":{"data":"FE1800000000","st":"OK","er":""},"8":{"data":"267D0000","st":"OK","er":""},"9":{"data":"245B0000","st":"OK","er":""},"10":{"data":"00","st":"OK","er":""},"12":{"data":"00","st":"OK","er":""},"14":{"data":"060A6200","st":"OK","er":""},"63":{"data":"24","st":"OK","er":""},"90":{"data":"1B00","st":"OK","er":""},"92":{"data":"0000","st":"OK","er":""},"93":{"data":"01010B64B3","st":"OK","er":""},"94":{"data":"F0554B00","st":"OK","er":""},"790":{"data":"0:07030F308000100005071B00BE03960000000000000088066F081F0220001D00","st":"OK","er":""},"791":{"data":"1:C000000003426705251DD600E20000006C003B00000000000000910C0C017000","st":"OK","er":""},"792":{"data":"2:003C1E000000000047000000A00F2C011E000306A00F2C010036D3031E0000FF","st":"OK","er":""},"793":null,"794":null,"lu":"2\/3\/2021 - 15:34:58"}}],"errors":[],"waterscene_time":null,"waterscene_time_garden":null,"waterscene_time_heater":null,"waterscene_time_washing":"2","waterscene":"normal","disable_time":"","waterscene_normal":"5","hardness_shower":"4","hardness_watering":"10","hardness_heater":"1","hardness_washing":"1","sleepmode_time":null,"holiday_mode":null,"update":"0"}],"status":"ok","token":"TOKEN_VON_OBEN","command":"get device data"}`

Ich denke, bis dahin ist das klar. Die Requests, die aber in der Cloud benötigt werden scheinen aber anders zu sein, als die, die für die PRO Variante bereits implementiert sind. So ist zum Beispiel, der Request für die Umstellung der Wunschwasserhärte** folgender:

`https://www.myjudo.eu/interface/?token=TOKEN_VON_OBEN&group=register&command=write%20data&serial_number=6827XXXXX5eb&dt=0x33&index=60&data=5&da=0x1&role=customer&action=normal`

​	--> Ergebnis: `{"status":"ok","token":"TOKEN_VON_OBEN"}`

oder Starten der **Regeneration**:

`https://www.myjudo.eu/interface/?token=TOKEN_VON_OBEN&group=register&command=write%20data&serial_number=6827XXXXX5eb&dt=0x33&index=65&data=&da=0x1&role=customer`

​	--> Ergebnis: `{"status":"ok","token":"TOKEN_VON_OBEN"}`

Ich könnte anbieten die Requests zusammen zu schreiben und Dir weitergeben. Hat dann vielleicht nicht den gleichen Funktionsumfang wie die Pro-Variante, aber die Basics könnten so funktionieren. Wie lange der Token gültig ist, kann ich noch nicht sagen auf jeden Fall länger als 24h. Wie die Wassermengen übermittelt werden habe ich auch leider noch nicht rausgefunden. Könnte ich mich aber noch ein wenig mit beschäftigen. 

Wenn Du Dir vorstellen könntest, dass das klappen könnte, würde ich mich mal dran setzen um zu sehen, wie weit man kommt.

**Comment by arteck** [comment]
musste ich mir anschauen.. könten wir uns im discord treffen ??

**Comment by arteck** [comment]
@tommedIO @kramerlein @Brandy-f1 @mirage-111 

installiert mal die neue version ... die Cloud sollte jetzt gehen..

**Comment by Brandy-f1** [comment]
Hallo arteck,

Ich hab gerade die 1.0.5 installiert. Leider bleibt die Instanz ROT.
Habe die Instanz nochmal gelöscht, und neu angelegt. Der IOBroker wurde auch neu gestartet.
Leider blieb das Verhalten gleich.

anbei noch der Auszug aus meinem LOG.
![LOG_Judosoft_20210323](https://user-images.githubusercontent.com/60137562/112283150-1de63880-8c88-11eb-8918-3ad9e68897af.jpg)

In den Haupteinstellungen habe ich meinen User und mein Passwort sowie den Cloud Login benutzt.
Die IP hab ich gelöscht

Ich hoffe es hilft weiter.

VG

Brandy

**Comment by arteck** [comment]
hast genau die Fehlerhafte Version erwischt

@Brandy-f1 installier JETZT mal neu

**Comment by Brandy-f1** [comment]
So jetzt hab ichs nochmal installiert ;-)

Scheint auf den ersten Blick zu funktionieren.
Werd das die nächsten Tage mal testen und melde mich wieder!

Vielen Dank für die Umsetzung und die Hilfe!

VG

Brandy

**Comment by tommedIO** [comment]
Top! Vielen Dank. Bei mir funktioniert es! Das ist wirklich gut geworden!

Eine kleine Anmerkung: WaterTotal und WaterTotalOut (weiß einer, was das für eine Größe ist?) wird in Litern übertragen hat aber die Einheit m³. D.h. dort passt es um den Faktor 1000 nicht. Ist aber nur ein kleiner Schönheitsfehler.

**Comment by kramerlein** [comment]
Ich für meinen Teil kann mich auch nur bedanken. Scheint erstmal alles zu funktionieren. Lediglich das mit dem Gesamtwasser (Faktor 1000) kann ich auch bestätigen und alle meine Monatsbilanzen stehen aktuell bei 0 m³. aber ich weiß nicht, ob sich das über die Zeit erst aufbaut.

Viele Grüße und vielen Dank
kramerlein

**Comment by thstickel** [comment]
Ich möchte mich auch noch mal bei @arteck bedanken für die Umsetzung. Freut mich, dass es bis jetzt bei allen funktioniert. 
Bzgl. des  Unterschieds zwischen WaterTotal und WaterTotalOut haben wir uns gestern auch diskutiert. Wir waren der Auffassung, dass WaterTotal die Menge an Wasser ist, die in die Anlage rein geht und WaterTotalOut, die Menge, die wieder raus geht abzgl. des Wassers, welches durch die Regeneration direkt wieder "raus gewaschen" wird - ist aber nur eine Vermutung. Vielleicht kann das der eine oder andere mal testen oder überprüfen. Sicher waren wir uns auch nicht. 
Die Einheit m³ ist uns nicht aufgefallen. Aber die Angabe ist in Litern bzw. Faktor 1000. 
Die Monatsbilanzen werden bei dieser Version (noch) nicht ausgelesen. Sollte das für Euch wichtig sein, müsstet Ihr noch mal bei Arthur Bescheid geben. Für mich war es nicht wichtig. @arteck Ich könnte dann anbieten, dass wir uns noch mal zusammenschließen und schauen, ob wir die Werte finden.
Einen Hinweis habe ich noch: Ich habe testhalber die Pollingzeit mal auf 10 Sekunden gestellt, was für die Live-Wassermenge ganz interessant wäre und habe nach 8h keine Probleme gehabt. Dies könnte ggf. auch noch mal getestet werden.

**Comment by tommedIO** [comment]
Bei mir steht TotalWater auf 160000 und TotalWaterOut auf 90000. Das wäre schon extrem, wenn 70000 für die Regeneration drauf gehen. 

Wie passen eure Werte für die Salzreichweite zu den Werten aus der App? Bei mir sagt die App 9 Wochen und die Schnittstelle 61Tage.

**Comment by kramerlein** [comment]
Vielen Dank für die Infos.

Bezüglich Monatswerte finde ich die Angaben nicht wahnsinnig wichtig, sondern nur ein "nice to have". Wenn ihr es noch erweitern wollt, wäre ich dankbar, würde aber auch sehr gut damit leben können, wenn diese Funktionalität nicht mit drin ist.

Bezüglich der Polling Zeit habe ich jetzt auch mal 10 Sekunden eingetragen und gebe bescheid, falls ich damit Probleme bekomme. Bis jetzt läuft es problemfrei.

Bezüglich Salzreichweite stehen bei mir 37 Tage zu 5 Wochen in der App. Da scheint also in der App einfach auf volle Wochen gerundet zu werden.

Bezüglich TotalWater steht bei mir der Wert auf 151420 l zu 115801 l bei 464 Regenerationen (laut App), das würde bedeuten, dass meine Anlage etwa 76,8 l pro Regeneration verbraucht. Laut Betriebsanleitung sollten es nur 25 l sein.  Ist also unwahrscheinlich, dass es ausschließlich die Regenerationen sind. Hat jemand der zusätzlich seine Wasseruhr im IOBroker hat mal verglichen wie genau die Werte übereinstimmen? Bei mir ist das bis jetzt leider nur in Planung und noch nicht umgesetzt.

Grüße
