### ISSUE TITLE
Adapter always stops

### ISSUE THREAD

**Issue by muhlatte** [arteck/ioBroker.judoisoft#21]
Hello guys,

unfortunately my judoisoft adapter always stops due to an error you see in my log below. Can you help me with this?

Thanks in advance!
Daniel

`

<html>
<body>

judoisoft.0 | 2022-04-25 11:34:10.785 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
judoisoft.0 | 2022-04-25 11:34:10.782 | info | terminating
judoisoft.0 | 2022-04-25 11:34:10.778 | info | cleaned everything up...
judoisoft.0 | 2022-04-25 11:34:10.747 | error | Converting circular structure to JSON --> starting at object with constructor 'TLSSocket' \| property 'parser' -> object with constructor 'HTTPParser' --- property 'socket' closes the circle
judoisoft.0 | 2022-04-25 11:34:10.745 | error | TypeError: Converting circular structure to JSON --> starting at object with constructor 'TLSSocket' \| property 'parser' -> object with constructor 'HTTPParser' --- property 'socket' closes the circle at JSON.stringify (<anonymous>) at judoisoftControll.getInfosCloud (/opt/iobroker/node_modules/iobroker.judoisoft/main.js:276:58) at processTicksAndRejections (internal/process/task_queues.js:95:5)
judoisoft.0 | 2022-04-25 11:34:10.742 | error | unhandled promise rejection: Converting circular structure to JSON --> starting at object with constructor 'TLSSocket' \| property 'parser' -> object with constructor 'HTTPParser' --- property 'socket' closes the circle
judoisoft.0 | 2022-04-25 11:34:10.739 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
judoisoft.0 | 2022-04-25 11:33:05.610 | info | State value to set for "judoisoft.0.Maintenance" has to be type "number" but received type "string"
judoisoft.0 | 2022-04-25 11:33:05.590 | info | State value to set for "judoisoft.0.ServiceDays" has to be type "number" but received type "string"
judoisoft.0 | 2022-04-25 11:32:04.438 | info | State value to set for "judoisoft.0.Maintenance" has to be type "number" but received type "string"
judoisoft.0 | 2022-04-25 11:32:04.418 | info | State value to set for "judoisoft.0.ServiceDays" has to be type "number" but received type "string"
judoisoft.0 | 2022-04-25 11:31:00.272 | info | State value to set for "judoisoft.0.Maintenance" has to be type "number" but received type "string"
judoisoft.0 | 2022-04-25 11:31:00.252 | info | State value to set for "judoisoft.0.ServiceDays" has to be type "number" but received type "string"
judoisoft.0 | 2022-04-25 11:29:59.654 | info | State value to set for "judoisoft.0.Maintenance" has to be type "number" but received type "string"
judoisoft.0 | 2022-04-25 11:29:59.634 | info | State value to set for "judoisoft.0.ServiceDays" has to be type "number" but received type "string"
judoisoft.0 | 2022-04-25 11:28:58.924 | info | State value to set for "judoisoft.0.Maintenance" has to be type "number" but received type "string"
judoisoft.0 | 2022-04-25 11:28:58.903 | info | State value to set for "judoisoft.0.ServiceDays" has to be type "number" but received type "string"
judoisoft.0 | 2022-04-25 11:28:56.518 | info | starting. Version 1.0.10 in /opt/iobroker/node_modules/iobroker.judoisoft, node: v14.19.1, js-controller: 4.0.21
judoisoft.0 | 2022-04-25 11:28:18.614 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
judoisoft.0 | 2022-04-25 11:28:18.611 | info | terminating
judoisoft.0 | 2022-04-25 11:28:18.607 | info | cleaned everything up...
judoisoft.0 | 2022-04-25 11:28:18.582 | error | Converting circular structure to JSON --> starting at object with constructor 'TLSSocket' \| property 'parser' -> object with constructor 'HTTPParser' --- property 'socket' closes the circle
judoisoft.0 | 2022-04-25 11:28:18.580 | error | TypeError: Converting circular structure to JSON --> starting at object with constructor 'TLSSocket' \| property 'parser' -> object with constructor 'HTTPParser' --- property 'socket' closes the circle at JSON.stringify (<anonymous>) at judoisoftControll.getInfosCloud (/opt/iobroker/node_modules/iobroker.judoisoft/main.js:276:58) at runMicrotasks (<anonymous>) at processTicksAndRejections (internal/process/task_queues.js:95:5)
judoisoft.0 | 2022-04-25 11:28:18.577 | error | unhandled promise rejection: Converting circular structure to JSON --> starting at object with constructor 'TLSSocket' \| property 'parser' -> object with constructor 'HTTPParser' --- property 'socket' closes the circle
judoisoft.0 | 2022-04-25 11:28:18.575 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().

</body>
</html>

`

**Comment by arteck** [comment]
stop the adapter and del all object ..
then restart

**Comment by muhlatte** [comment]
Leider funktioniert mein Adapter nach einem Umzug auf den Pi4 wieder nicht. Habe sowohl Cloud login als auch über IP Adresse probiert. Adapter geht kurz auf grün und dann auf rot. Mit der IP kommt folgender Log

`
<html>
<body>


judoisoft.0 | 2022-05-18 22:04:57.675 | warn | Terminated (UNCAUGHT_EXCEPTION): Without reason
-- | -- | -- | --
judoisoft.0 | 2022-05-18 22:04:57.673 | info | terminating
judoisoft.0 | 2022-05-18 22:04:57.671 | info | cleaned everything up...
judoisoft.0 | 2022-05-18 22:04:57.663 | error | Converting circular structure to JSON --> starting at object with constructor 'Object' \| property 'httpsAgent' -> object with constructor 'Agent' \| property 'sockets' -> object with constructor 'Object' \| ... \| property 'errored' -> object with constructor 'Object' --- property 'config' closes the circle
judoisoft.0 | 2022-05-18 22:04:57.662 | error | TypeError: Converting circular structure to JSON --> starting at object with constructor 'Object' \| property 'httpsAgent' -> object with constructor 'Agent' \| property 'sockets' -> object with constructor 'Object' \| ... \| property 'errored' -> object with constructor 'Object' --- property 'config' closes the circle at JSON.stringify (<anonymous>) at judoisoftControll.getInfoStaticLocal (/opt/iobroker/node_modules/iobroker.judoisoft/main.js:147:62) at processTicksAndRejections (internal/process/task_queues.js:95:5) at async judoisoftControll.onReady (/opt/iobroker/node_modules/iobroker.judoisoft/main.js:68:13)
judoisoft.0 | 2022-05-18 22:04:57.660 | error | unhandled promise rejection: Converting circular structure to JSON --> starting at object with constructor 'Object' \| property 'httpsAgent' -> object with constructor 'Agent' \| property 'sockets' -> object with constructor 'Object' \| ... \| property 'errored' -> object with constructor 'Object' --- property 'config' closes the circle
judoisoft.0 | 2022-05-18 22:04:57.659 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
judoisoft.0 | 2022-05-18 22:04:54.547 | warn | Read-only state "judoisoft.0.info.connection" has been written without ack-flag with value "false"
judoisoft.0 | 2022-05-18 22:04:54.539 | debug | get Information Static Local
judoisoft.0 | 2022-05-18 22:04:51.394 | debug | get statusURL for local
judoisoft.0 | 2022-05-18 22:04:50.941 | debug | create state
judoisoft.0 | 2022-05-18 22:04:50.939 | debug | base url https://192.168.178.93:8124/?group=
judoisoft.0 | 2022-05-18 22:04:50.904 | info | starting. Version 1.0.10 in /opt/iobroker/node_modules/iobroker.judoisoft, node: v14.19.2, js-controller: 4.0.23
judoisoft.0 | 2022-05-18 22:04:50.658 | debug | States connected to redis: 127.0.0.1:9000
judoisoft.0 | 2022-05-18 22:04:50.634 | debug | States create User PubSub Client
judoisoft.0 | 2022-05-18 22:04:50.632 | debug | States create System PubSub Client
judoisoft.0 | 2022-05-18 22:04:50.617 | debug | Redis States: Use Redis connection: 127.0.0.1:9000
judoisoft.0 | 2022-05-18 22:04:50.578 | debug | Objects connected to redis: 127.0.0.1:9001
judoisoft.0 | 2022-05-18 22:04:50.570 | debug | Objects client initialize lua scripts
judoisoft.0 | 2022-05-18 22:04:50.525 | debug | Objects create User PubSub Client
judoisoft.0 | 2022-05-18 22:04:50.523 | debug | Objects create System PubSub Client
judoisoft.0 | 2022-05-18 22:04:50.521 | debug | Objects client ready ... initialize now
judoisoft.0 | 2022-05-18 22:04:50.449 | debug | Redis Objects: Use Redis connection: 127.0.0.1:9001
judoisoft.0 | 2022-05-18 22:04:38.682 | warn | Terminated (NO_ADAPTER_CONFIG_FOUND): Without reason
judoisoft.0 | 2022-05-18 22:04:38.672 | error | adapter disabled


</body>
</html>

`

Ein Löschen des Objektbaums nach kurzzeitigem Stop brachte keine Abhilfe.
Liegt es eventuell daran, dass ich nebenzu ein pi-hole am laufen habe?

Herzlichen Dank für deine Hilfe arteck!

**Comment by arteck** [comment]
der Adapter hat kein zugrff mehr..und ja es kann am pi-hole liegen
