### ISSUE TITLE
NPM Version für iobroker 

### ISSUE THREAD

**Issue by bambi-arch** [arteck/ioBroker.judoisoft#22]
Super das es einen Adapter für Judo gibt! Bitte nach Test über npm zum Installieren für den iobroker zur Verfügung stellen! Danke im Voraus!

**Comment by arteck** [comment]
verstehe nicht was du willst ??

**Comment by bambi-arch** [comment]
Seit kurzem steht nun auch die Version im ioBroker zur Verfügung, ohne eine Installation über GitHub gehen zu müssen! Super danke, auch wenn du mich nicht verstanden hast!
