### ISSUE TITLE
Wünsch von weiteren Feldern

### ISSUE THREAD

**Issue by bambi-arch** [arteck/ioBroker.judoisoft#25]
Hallo,
in der App gibt es noch folgende Felder. Könnt dieses auch als Datenpunkt eingefügt werden? Danke im Voraus!!!

1. Leckageschutz (aktive) (Anzeige)
2. Urlaubsmodus starten (Button)
3. Wassersperren (Button)
4. Salzvorrat nachfüllen (kg) (Eingabe)
5. Gesamt-Regenerationszahl (Zahl)
6. Anzahl Wartungen (Zahl)
7. Wasserszenen (Auswahl)

**Comment by Brandy-f1** [comment]
Servus,

Soweit ich noch weis hat Arteck den Adapter bewusst klein gehalten und auf Statistikwerte usw. verzichtet.
Grund war die langsame Aktualisierung durch die Art der Komunikation.

Evtl kann Arteck hierzu nochwas sagen.

Zu deinen Punkten:
1. Sollte unter dem Datenpunkt "WaterStopStatus" zu finden sein.
2. Würd ich über externes Skript / Blockly lösen
3. Würd ich über externes Skript / Blockly lösen -> Datenpunkt "WaterStop"
4. Da bist ja eh vor der Anlage und kannst das direkt eingeben ;-)
5. Fällt meines Erachtens unter Statistik.
6. Fällt meines Erachtens unter Statistik.
7. Diese Geschichte hab ich über Blockly gelöst, mit Sleepmodus Restzeit und Anpassung der Wasserhärte.

Falls ich noch Infos geben kann, gerne.
Hab selbst ne i soft-safe.

VG

Brandy
