### ISSUE TITLE
Question regarding Button "Regeneration"

### ISSUE THREAD

**Issue by Claus1985** [arteck/ioBroker.judoisoft#26]
Hi All,

one question regarding the button regeneration. Is it just for triggering a manual regeneration or
should it also show if an automatic regeneration is ongoing (set true by the device when regenerating)?

I wanted to use it for measuring the energy consumption (3w standard standby consumption + 20w druring regeneration for my iSoft+).
But in the last two weeks the value was not changed and I start to believe that its just for manually triggering the process (which would not make sense?)?

I am using version 1.0.15 of the adapter.

Thx and brgds,

Claus

**Comment by Brandy-f1** [comment]
Hi Claus1985,

I think the button regeneration is only totriggering manual regeneration.

Best regards

Brandy

**Comment by Claus1985** [comment]
@arteck is it possible to change the value into one that can be set/changed?

thx and Brgs

**Comment by Claus1985** [comment]
Thx for the info. Is it possible to implement a status which shows if the regeneration is running at the moment?

**Comment by arteck** [comment]
the question is .. can i see this in the api

**Comment by Claus1985** [comment]
As far as I could find out it should be possible. In the following screenshot there are two values for regeneration.
One (52) with a parameter stop and one (53) without a parameter. So i guess that 53 should be the status.

**Comment by www-ShapeLabs-de** [comment]
I took a closer look at data record #791. 
It seems that the first hex digit after the colon is a flag that gives information about an running regeneration. 0xC0=regeneration not active, 0xC1 or 0xC3 regeneration running.
0xC1/0xC3 could provide information about which softener cartridge is currently being regenerated.
