### ISSUE TITLE
input/raw residual hardness

### ISSUE THREAD

**Issue by www-ShapeLabs-de** [arteck/ioBroker.judoisoft#27]
Hello,
for my project ( https://github.com/www-ShapeLabs-de/Judo-i-soft-save-plus-to-mqtt-bridge ) I used dataConverter.js as a guide to decode the data from the json-response. I noticed that raw residual hardness outputs is double as the expected value. 

At https://www.wasserhaerte.net/deutschland/index.html I get 14°dH displayed for my region and my plumber confirmed the value with a titration test while installing the system. The Judo-Device gives me a value of 28°dH.

"790":{"data":"0:00030F30000010000301180059038A00000000000000220C0000**1C**0A20001A00","st":"OK","er":""},

0x1C = 28

Could it be that the device doubles the value to show a resolution of 0.5°dH with the hex value?

Has anyone observed similar and can verify my assumption that this value must be divided by 2?

**Comment by arteck** [comment]
look in the app plz

**Comment by www-ShapeLabs-de** [comment]
my app doesn't show the input hardness :-/

**Comment by arteck** [comment]
then make it local in your system

https://github.com/arteck/ioBroker.judoisoft/blob/8e22377bc7e2e60527ab60151ba054c22f408c09/main.js#L234
