### ISSUE TITLE
Fehlermeldung bei Installation

### ISSUE THREAD

**Issue by joker17177** [arteck/iobroker.judoisoft#3]
@arteck

Ich bekomme beim installieren der letzten Adapterversion folgende Fehlermeldung:

Fertig mit Fehler: internal/modules/cjs/loader.js:1044 throw err; ^SyntaxError: /opt/iobroker/node_modules/iobroker.judoisoft/io-package.json: Unexpected token } in JSON at position 170 at parse () at Object.Module._extensions..json (internal/modules/cjs/loader.js:1041:22) at Module.load (internal/modules/cjs/loader.js:863:32) at Function.Module._load (internal/modules/cjs/loader.js:708:14) at Module.require (internal/modules/cjs/loader.js:887:19) at require (internal/modules/cjs/helpers.js:74:18) at Upload.uploadAdapter (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupUpload.js:481:19) at /opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:1781:24 at ChildProcess. (/opt/iobroker/node_modules/iobroker.js-controller/lib/setup/setupInstall.js:478:47) at ChildProcess.emit (events.js:314:20)

Kann damit leider nix anfangen...

**Comment by arteck** [comment]
sry jetzt

**Comment by joker17177** [comment]
Vielen Dank...!!!
