### ISSUE TITLE
Täglicher Wasserverbrauch...

### ISSUE THREAD

**Issue by tiigaaa** [arteck/ioBroker.judoisoft#34]
Hallo, wäre es möglich den täglichen Wassserverbauch auszulesen?
ich habe den CLOUD LOGIN aktiviert, da über die direktre IP der Adapter nicht grün wird.
Bei den Kollegen von FHEM seiht esso aus als würden die das können. https://wiki.fhem.de/wiki/JUDO_iSoft_Plus

Das wäre echt cool  super, danke
LG

**Comment by arteck** [comment]
was ist mit dem WaterTotal DP

**Comment by tiigaaa** [comment]
Ja der wird befüllt, aber in der App wird jeden Tag ein Balken erstellt mit dem wert.

Wenn es nicht geht an die Daten zukommen könnte ich mir was basteln. Immer um 24:00 den aktuellen Wert mit dem vom Vortag 24:00 Uhr vergleichen und den Unterschied in eine Register oder so packen.

**Comment by arteck** [comment]
ist nicht dein ernst oder... na klar musst du selber rechnen
