### ISSUE TITLE
Kein schreiben der Waserhärte mehr möglich

### ISSUE THREAD

**Issue by Brandy-f1** [arteck/ioBroker.judoisoft#35]
Sobal ich den Wert der Wunschwasserhärte ändern möchte geht der Adapter auf Stop.

Ich vermute mal das hat evtl. mit der Umstellung bei JUDO und deren API zutun.

Wenn noch weitere Infos benötigt werden, bitte kurz melden.

Im log hab ich das zweimal probiert.

Hier der Auszug aus dem LOG:
<html><body>

host.iobroker | 2024-02-22 19:29:18.895 | error | instance system.adapter.judoisoft.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
judoisoft.0 | 2024-02-22 19:29:18.126 | error | Request failed with status code 500
judoisoft.0 | 2024-02-22 19:29:18.126 | error | Error:  Request failed with status code 500     at createError  (/opt/iobroker/node_modules/iobroker.judoisoft/node_modules/axios/lib/core/createError.js:16:15)     at settle  (/opt/iobroker/node_modules/iobroker.judoisoft/node_modules/axios/lib/core/settle.js:17:12)     at IncomingMessage.handleStreamEnd  (/opt/iobroker/node_modules/iobroker.judoisoft/node_modules/axios/lib/adapters/http.js:293:11)     at IncomingMessage.emit (node:events:529:35)     at endReadableNT (node:internal/streams/readable:1400:12)     at process.processTicksAndRejections  (node:internal/process/task_queues:82:21)
judoisoft.0 | 2024-02-22 19:29:18.121 | error | unhandled promise rejection: Request failed with status code 500
judoisoft.0 | 2024-02-22 19:29:18.112 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().
host.iobroker | 2024-02-22 19:28:02.582 | error | instance system.adapter.judoisoft.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
judoisoft.0 | 2024-02-22 19:28:01.855 | error | Request failed with status code 500
judoisoft.0 | 2024-02-22 19:28:01.854 | error | Error:  Request failed with status code 500    at createError  (/opt/iobroker/node_modules/iobroker.judoisoft/node_modules/axios/lib/core/createError.js:16:15)     at settle  (/opt/iobroker/node_modules/iobroker.judoisoft/node_modules/axios/lib/core/settle.js:17:12)     at IncomingMessage.handleStreamEnd  (/opt/iobroker/node_modules/iobroker.judoisoft/node_modules/axios/lib/adapters/http.js:293:11)     at IncomingMessage.emit (node:events:529:35)    at endReadableNT  (node:internal/streams/readable:1400:12)    at  process.processTicksAndRejections  (node:internal/process/task_queues:82:21)
judoisoft.0 | 2024-02-22 19:28:01.852 | error | unhandled promise rejection: Request failed with status code 500
judoisoft.0 | 2024-02-22 19:28:01.845 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().

</body>
</html>

**Comment by Brandy-f1** [comment]
Update: Eine Bedienung übder die Judo App ist problemlos möglich. Hatte ich vorher vergessen

**Comment by arteck** [comment]
installier nochmal von GIt

**Comment by Brandy-f1** [comment]
Leider keine Verbesserung,

Hier der auszug aus dem LOG: (im DEBUG)
<html><body>

host.iobroker | 2024-02-23 21:43:08.161 | error | instance system.adapter.judoisoft.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
-- | -- | -- | --
judoisoft.0 | 2024-02-23 21:43:07.281 | error | Exception-Code: ERR_BAD_RESPONSE: Request failed with status code 500
judoisoft.0 | 2024-02-23 21:43:07.280 | error | AxiosError:  Request failed with status code 500    at settle  (/opt/iobroker/node_modules/axios/dist/node/axios.cjs:1967:12)    at  IncomingMessage.handleStreamEnd  (/opt/iobroker/node_modules/axios/dist/node/axios.cjs:3066:11)    at  IncomingMessage.emit (node:events:529:35)    at endReadableNT  (node:internal/streams/readable:1400:12)    at  process.processTicksAndRejections  (node:internal/process/task_queues:82:21)    at Axios.request  (/opt/iobroker/node_modules/axios/dist/node/axios.cjs:3877:41)    at  process.processTicksAndRejections  (node:internal/process/task_queues:95:5)    at async  judoisoftControll.setCommandStateCloud  (/opt/iobroker/node_modules/iobroker.judoisoft/main.js:474:29)
judoisoft.0 | 2024-02-23 21:43:07.280 | error | unhandled promise rejection: Request failed with status code 500
judoisoft.0 | 2024-02-23 21:43:07.278 | error | Unhandled  promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().


</body>
</html>

Wenn ich noch was anderes tun kann, gerne

**Comment by eviw** [comment]
Bei mir ähnlich. Wenn ich ResidualHardness im Objekt ändere, geht der Adapter auf gelb und das Schreiben schlägt fehl.
Log:
`judoisoft.0 2024-03-05 22:34:28.257	error	set ResidualHardness Local ERROR
judoisoft.0 2024-03-05 22:33:30.835	error	getInfos ERROR
judoisoft.0 2024-03-05 22:33:28.261	debug	set StandBy Localfalse
judoisoft.0 2024-03-05 22:33:28.260	debug	--> stateID judoisoft.0.StandBy changed: false (ack = false)
judoisoft.0 2024-03-05 22:33:28.252	debug	set ResidualHardness Local4
judoisoft.0 2024-03-05 22:33:28.252	debug	--> stateID judoisoft.0.ResidualHardness changed: 4 (ack = false)`

Änderungen der Wasserhärte in der App oder direkt am Gerät werden über den Adapter korrekt aktualisiert, aber natürlich nur so lange der Adapter auf grün steht.

**Comment by eviw** [comment]
Ich kann nicht einschätzen, ob es mit dem issue zusammenhängt, aber auch der Alexa Skill Judo funktioniert nicht mehr. Fehlermeldung "Verbindung zum Gerät konnte nicht hergestellt werden". Ich habe die Fa. Judo angeschrieben und heute folgende Antwort erhalten:
"... der Dienstleiter ist bereits in Arbeit. 
Wir gehe davon aus, dass es nächste Woche behoben ist. 


Mit freundlichen Grüßen aus Winnenden
Ihr JUDO Kundendienst"
