### ISSUE TITLE
1.0.2 Fehlermeldung

### ISSUE THREAD

**Issue by joker17177** [arteck/iobroker.judoisoft#4]
Hallo!

Bekomme seit dem Installieren der letzten Version folgende Fehlermeldung:

judoisoft.0 | 2021-01-27 21:48:36.188 | info | (16860) Terminated (NO_ERROR): Without reason
judoisoft.0 | 2021-01-27 21:48:36.186 | info | (16860) terminating
judoisoft.0 | 2021-01-27 21:48:36.133 | info | (16860) cleaned everything up...
judoisoft.0 | 2021-01-27 21:48:36.132 | error | (16860) TypeError: Assignment to constant variable. at judoisoftControll.getTokenFirst (/opt/iobroker/node_modules/iobroker.judoisoft/main.js:326:23) at judoisoftControll.onReady (/opt/iobroke
judoisoft.0 | 2021-01-27 21:48:36.130 | error | (16860) unhandled promise rejection: Assignment to constant variable.
judoisoft.0 | 2021-01-27 21:48:36.129 | error | Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
judoisoft.0 | 2021-01-27 21:48:36.065 | info | (16860) starting. Version 1.0.2 in /opt/iobroker/node_modules/iobroker.judoisoft, node: v12.20.0, js-controller: 3.1.6

**Comment by joker17177** [comment]
oder folgende:

judoisoft.1 | 2021-01-27 21:58:44.244 | info | (17441) Terminated (NO_ERROR): Without reason
judoisoft.1 | 2021-01-27 21:58:44.242 | info | (17441) terminating
judoisoft.1 | 2021-01-27 21:58:44.171 | info | (17441) cleaned everything up...
judoisoft.1 | 2021-01-27 21:58:44.169 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
judoisoft.1 | 2021-01-27 21:58:44.169 | error | at judoisoftControll.onReady (/opt/iobroker/node_modules/iobroker.judoisoft/main.js:57:29)
judoisoft.1 | 2021-01-27 21:58:44.169 | error | at judoisoftControll.getTokenFirst (/opt/iobroker/node_modules/iobroker.judoisoft/main.js:326:23)
judoisoft.1 | 2021-01-27 21:58:44.169 | error | (17441) TypeError: Assignment to constant variable.
judoisoft.1 | 2021-01-27 21:58:44.167 | error | (17441) unhandled promise rejection: Assignment to constant variable.
Unhandled | 2021-01-27 21:58:44.166 | error | promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch().
judoisoft.1 | 2021-01-27 21:58:44.105 | info | (17441) starting. Version 1.0.2 in /opt/iobroker/node_modules/iobroker.judoisoft, node: v12.20.0, js-controller: 3.1.6

**Comment by arteck** [comment]
korrigiert
