### ISSUE TITLE
Adapter wird nicht mehr grün

### ISSUE THREAD

**Issue by tiigaaa** [arteck/ioBroker.judoisoft#40]
Hallo,

seit einigen Tagen kommt der Adapter nicht mehr hoch.
Ich habe am System nichts angefasst und die APP von Judo funktionmiert noch gleich wie immer.
Hab das nur ich? 

LG
Danke

**Comment by Brandy-f1** [comment]
Hallo, hab das gleiche Problem,

Die Details hab ich grad im Adapter Chat eingefügt.

Restart des Systems, Eingabe der Benutzerdaten usw. brachte keien Erfolg.
![Judo Adapter Info](https://github.com/user-attachments/assets/b85fdeb3-041b-442f-8a16-9d19b4a1f438)
![Log_Error](https://github.com/user-attachments/assets/09fc21db-b36c-44bd-b7f5-c863abdd5b21)
![Sysinfos](https://github.com/user-attachments/assets/9a1506ca-1956-4294-946a-47dfaac3afd7)

**Comment by bambi-arch** [comment]
Hab das gleiche Problem. Als ich den Hacken bei Cloudlogin raus habe ist der Adapter wieder grün

**Comment by tommedIO** [comment]
Bei mir gehts auch seit ein paar Tagen nicht mehr. Das Rausnehmen des Cloud-Login hat leider keine Besserung gebracht. Protokoll ist identisch zu Brandy

**Comment by muhlatte** [comment]
Selbiges bei mir. Login über die myjudo.eu Seite geht ebenfalls einwandfrei.

@arteck 
Falls du ein Gerät zum Testen brauchst gib Bescheid!

**Comment by tiigaaa** [comment]
HI,
ich hab bei den Jungs von HA was gefunden:
https://github.com/www-ShapeLabs-de/Judo-i-soft-save-plus-to-mqtt-bridge/pull/24/files

da gibt es ein workaround. Leider bin ich kein programmierer aber eventuell hift es.

**Comment by muhlatte** [comment]
@Apollon77 
Kannst du vielleicht unterstützen? Arthur scheint gerade ja nicht so aktiv zu sein.

**Comment by Apollon77** [comment]
Jetzt gebt @arteck  doch mal Zeit zu reagieren ...

**Comment by Brandy-f1** [comment]
Falls eine Anlage zum Testen oder erweiterter Fehlersuche benötigt wird, einfach melden. Dann könnte ich damit unterstützen.

**Comment by arteck** [comment]
so checkt mal die neue version

**Comment by Brandy-f1** [comment]
Habs gerade probiert, soweit wird der Adapter wieder grün mit Cloud Login. Ein schreiben der Wasserhärte geht auch.
Die nächsten Tage werd ich noch weiter testen.

Vielen Dank schon mal!

**Comment by muhlatte** [comment]
Bei mir auch, alles bestens. Vielen lieben Dank, Arthur

**Comment by bambi-arch** [comment]
Geht wieder. Dankeschön !!!!

**Comment by SmartHomer0** [comment]
Ja, der Adapter funktioniert wieder ohne Probleme. Danke für Deine Mühen!

**Comment by Apollon77** [comment]
@arteck Wen du magst dann verwerise auf das issue bei stable fast-track

**Comment by tiigaaa** [comment]
Hi, dankeeeeeeeee
Geht wieder. Ticket kann zugemacht werden. :)

**Comment by 1of4** [comment]
Hallo,
ich habe auch das Problem mit der Version 1.1.0.
Wie komme ich denn an die neue 1.1.1 ?
Grüße
Alex

**Comment by fnp13** [comment]
Im IOBroker den Expertenmodus anschalten. Dann erscheint unter Adapter das Github Icon. 

![image](https://github.com/user-attachments/assets/385b905d-c539-4612-9857-0045be9d7dbe)

Dann im zweiten Reiter (von Github) nach dem judoisoft Adapter suchen und installieren.

![image](https://github.com/user-attachments/assets/9cb35844-dcc5-42cf-aec8-511f09934536)

**Comment by 1of4** [comment]
Super, wieder etwas gelernt!
Adapter läuft rund, ich bekomme wieder Daten.
Vielen Dank
Alex
