### ISSUE TITLE
Keine Daten ausgelesen / Status connected

### ISSUE THREAD

**Issue by CG28** [arteck/iobroker.judoisoft#5]
Hi,

die Instanz wird grün ohne Fehler angezeigt. Ich habe die interne IP-Adresse angegeben, Nutzername und Passwort. Der indicator.connected zeigt den Status "connected" an. Allerdings fehlen sämtliche Werte.

Entgegen indicator.connected, zeigt der Status connected eine Zeile drunter "ERROR" an.

Im Log erhalte ich folgende MEldung (alle 60 Sekunden entsprechend der Refreshtime):

judoisoft.0 | 2021-02-13 08:54:44.356 | error | at processTicksAndRejections (internal/process/task_queues.js:97:5)
-- | -- | -- | --
judoisoft.0 | 2021-02-13 08:54:44.356 | error | at judoisoftControll.getTokenFirst (/opt/iobroker/node_modules/iobroker.judoisoft/main.js:361:69)
judoisoft.0 | 2021-02-13 08:54:44.356 | error | (28371) TypeError: Cannot read property 'data' of undefined
judoisoft.0 | 2021-02-13 08:54:44.355 | error | (28371) unhandled promise rejection: Cannot read property 'data' of undefined
Unhandled | 2021-02-13 08:54:44.354 | error | promise rejection. This error originated either by throwing inside of  an async function without a catch block, or by rejecting a promise which  was not handled with .catch().

**Comment by arteck** [comment]
installier nochmal eu bitte .. hatte noch ein fehler..

**Comment by CG28** [comment]
Hi, also was jetzt geht ist, dass die Ampel auf rot bleibt und es jetzt nur noch den connection status gibt bei dem ERROR angezeigt wird.

Was genau erwartet demm der Adapter eigentlich unter der IP Adresse? Die Seite die dort erscheint zeigt nämlich auch keinerleit Daten zu Wasserverbrauch, Wasserhärte etc. an. An sehe ich alles nur über meine App über die Cloudverbindung. 

Unter der IP der Enthärtungsanlage erscheint folgende Seite:

![Screenshot 2021-02-14 145200](https://user-images.githubusercontent.com/63516077/107878627-4e41f680-6ed4-11eb-8848-feda7db5c358.png)

**Comment by Brandy-f1** [comment]
Servus,

Welchen Typ der Judo Anlage hast Du denn?
Ich hab eine isoft-safe. Der Cloud Login geht nicht, Sieh Dir bitte das andere Issue an, da hatten wir schon versucht an die Daten ranzukommen.
@arteck : Ich hoffe das passt so noch ;-)

**Comment by arteck** [comment]
genau .. und es bringt nix die IP der Cloud anzugeben.. bis jetzt läuft der adapter nicht mit der -safe

**Comment by CG28** [comment]
Hallo zusammen,

Dann habe ich den ersten Thread falsch verstanden, las sich wie ein Feature und nicht ein Issue. Ich dachte ihr wolltet zusätzlich den Cloudzugang einbinden.

Kurz: ja ich habe die i-soft safe . Dann mach ich hier zu und es geht im anderen Thread weiter.

Immerhin konnte so aber der Bug mit der Statusanzeige gelöst werden 😂.
