### ISSUE TITLE
Probleme beim Adapterstart

### ISSUE THREAD

**Issue by joker17177** [arteck/iobroker.judoisoft#6]
@arteck

Hallo!

Ich habe seit dem letzten Update Probleme den Adapter zu starten. Im Log sehe ich nur "system.adapter.judoisoft.0 invalid mode".
Habe den Adapter schon mehrfach neu installiert, aber leider ohne Erfolg.
Würde mich über Deine Hilfe sehr freuen. Vielen Dank im Voraus!

**Comment by arteck** [comment]
schau jetzt

**Comment by joker17177** [comment]
jetzt startet der Adapter und verbindet sich mit auch mit der Isoft, allerdings mit folgender Meldung:

host.IOBroker | 2021-02-18 21:01:01.028 | info | Do not restart adapter system.adapter.judoisoft.0 because desired by instance
-- | -- | -- | --
host.IOBroker | 2021-02-18 21:01:01.027 | error | instance system.adapter.judoisoft.0 terminated by request of the instance itself and will not be restarted, before user restarts it.
judoisoft.0 | 2021-02-18 21:01:00.512 | warn | (1890) Got terminate signal. Checking desired PID: 1919 vs own PID 1890
judoisoft.0 | 2021-02-18 21:01:00.507 | info | (1890) Terminated (ADAPTER_REQUESTED_TERMINATION): Without reason
judoisoft.0 | 2021-02-18 21:01:00.506 | info | (1890) terminating
judoisoft.0 | 2021-02-18 21:01:00.504 | info | (1890) cleaned everything up...
judoisoft.0 | 2021-02-18 21:01:00.502 | warn | (1890) Got terminate signal. Checking desired PID: 0 vs own PID 1890
host.IOBroker | 2021-02-18 21:01:00.498 | info | instance system.adapter.judoisoft.0 started with pid 1919
host.IOBroker | 2021-02-18 21:01:00.465 | info | "system.adapter.judoisoft.0" enabled

Kann ich das ignorieren?

**Comment by arteck** [comment]
alles gut.. das ist ein Folgefehler.. bekommst du auch Daten ??

**Comment by joker17177** [comment]
Vielen Dank für Deine schnelle Hilfe...
