### ISSUE TITLE
Cloud Login Datenpunkte und Einheiten

### ISSUE THREAD

**Issue by Brandy-f1** [arteck/ioBroker.judoisoft#8]
Hallo Arteck,
ich habe mich die letzten Tage mit den Datenpunkten des Cloudlogins auseinandergesetzt.
Bei einigen Datenpunkten kommen keine Werte, andere stimmen in der Einheit nicht.
Meine Erkenntnisse findest Du in der angehängten Excel Tabelle.

Ich hab die Infos nur mal schnell zu Datei gebracht, ohne auf die Formattierung usw. Wert zu legen.
Wenn ich am Adapter helfen kann, mach ich das gerne, hab aber noch so gar keine Ahnung was wo anzupassen wäre.
Ich könnte Dir z.B. helfen die Dokumentation für den Teil des Cloud Login weiterzutreiben wenn es hilft.

[Infos.xlsx](https://github.com/arteck/iobroker.judoisoft/files/6254357/Infos.xlsx)

Ich wünsch Dir noch Frohe Ostern bis bald!

VG

Brandy

**Comment by arteck** [comment]
schau ich mir mal an

**Comment by Brandy-f1** [comment]
ServusArteck,

Ich hab gerade die neue Version getestet. Leider startet der Adapter nicht mehr.
Ich hab Ihn auf Debug gestellt und das Log gesichert.


[LOG_20210409.zip](https://github.com/arteck/iobroker.judoisoft/files/6285186/LOG_20210409.zip)

Evtl. hab ich einen Fehler gemacht.

Hier meine Vorgehensweise:

1. Alle Objekte unter dem Instanzordner gelöscht
2. Installation des Adapters von GIT
3. Jetzt war der Instanz Ordner judosoft.0 weg.
4. Löschen der Instanz
5. Neu Installieren aus GIT
6. Neue Instanz angelegt
7. Instanz Ordner wieder erzeugt ist aber weitgehend leer

![grafik](https://user-images.githubusercontent.com/60137562/114170403-32d2f500-9933-11eb-810b-d3b4b951faee.png)

Ich hoffe das hilft Dir weiter.

VG

Brandy

**Comment by arteck** [comment]
so wie ist jetzt hier der stand ??

**Comment by Brandy-f1** [comment]
Servus, ich hatte Dir die Excle vor einiger Zeit in Discord zugesandt. Evtl hast Du die nicht gesehen.
Hier noch mal der aktuelle Stand.
[Infos_20210422.xlsx](https://github.com/arteck/iobroker.judoisoft/files/6410909/Infos_20210422.xlsx)

Die Einheiten sehen gut aus, die Tabelle hab ich noch um die Limits aus der Judo App erweitert.

Beim Datenpunkt der Residual dardness gibt es noch folgendes Problem:
Werte 10- 19 werden mit 16 -25 überschrieben somit Eingabewert + 6.
Bei Werten 20 -29 ergibt sich +12 usw.
Ich kann leider nicht sagen wo das herkommt, da bei eingaben 1- 9 alles OK ist.
Beim Datenpunkt SerialNumber wird die MAC-Adresse des LAN-Moduls angezeigt.

Die Infos hab ich in der Tabelle zusamengefasst.

VG

Brandy

**Comment by arteck** [comment]
16 -25 überschrieben somit Eingabewert + 6.

was heisst das .. wenn du 20 einträgst wird dann mit 26 quittiert ??

**Comment by Brandy-f1** [comment]
Servus,

fast.

Wenn ich einen Wert 10 - 19 eingebe, wird nach einigen Sekunden der eingegebene Wert um 6 höher zurückgegeben.

z.B 12 = Rückgabe 18

Bei Eingaben zwischen 20 - 29 wird nach einigen Sekunden der eingegebene Wert + 12 zurückgegeben.

z.B 21 = Rückgabewert 33

Bei 30 - 39 sind es dann + 18; weiter hab ichs nicht mehr getestet, da es sowieso nichtmehr relevante Werte wären.

In der Judo App kann man sowieso nur Werte zwische 1 - 12 °dH eingeben.

In der Excel hab ich die Grenzen von Judo mal eingetragen, evtl. hilft es dir weiter.

Du kannst es gerne mal austesten, deinen User hab ich noch aktiv gelassen.

Ich hoffe ich konnte es verständlich erklären.

Wir können uns gerne später auch i Discord treffen.

**Comment by arteck** [comment]
dann begrenzen wir den eingabe wert auf max 12.. wenn man es in der app ehh nur bis 12 eingeben kann

**Comment by Brandy-f1** [comment]
Ich denke das ist das beste, bleibt dann nur noch das Problem mit den Werten 10 - 12 hier wird dann ja immer noch der Eingabewert um 6 erhöht zurückgegeben. Hast Du hierzu schon was eingrenzen könnren?

Weiter oben findest du meine Exel vom 22.04.2021, hier hab ich die Grenzen von Judo aufgeführt.

**Comment by Brandy-f1** [comment]
Wenn es ne neue Version zum Testen gibt, sag einfach kurz Bescheid.

**Comment by Brandy-f1** [comment]
Mittlerweile hab ich die 1.0.9 installiert, da ich einen Crash meines Raspis hatte.
Leider besteht das Problem mit den Werten der Wasserhärte >10 immer noch. Leider keine Ahnung wo das her kommt.
@ Arteck: Wenn du wieder den Zugang zu meiner Anlage für Tests benötigst, sag mir bitte Bescheid,
hab deinen User momentan deaktiviert.

**Comment by feuh** [comment]
Hallo,

bei mir werden die selben Datenpunkte nicht gefüllt. Gibt es schon einen ansatz, wo das herkommen könnte?

**Comment by Brandy-f1** [comment]
Morgen, hab ja schon seit längerem die 1.0.10 installiert, leider besteht das Problem mir dem "falschen" Rückgabewert der ResidualHardness wie am 16. Mai beschriebnimmer noch. bin mir aber keineswegs sicher ob das durch den Adapter verursacht wird. die Werte wurden ja auf 1 - 12 °dH begrenzt. Momentan lös ich das so, daß ich nur Werte <10 verwende bzw. bem Gartengiessen mit einem höheren Rückgabewert lebe.

Bitte jetzt schon um Entschuldigung wenn ich evtl. die flaschen Bezeichnungen "Rückgabewert" benutz hab ;-) mr fällt nur nix besseres ein.
