### ISSUE TITLE
UNCAUGHT_EXCEPTION

### ISSUE THREAD

**Issue by feuh** [arteck/iobroker.judoisoft#9]
Hallo Arteck,

ich bin noch recht neu bei ioBroker und versuche gerade meine Judo isoftSafe einzubinden.

Leider wird keine Verbindung aufgebaut. Vom Host wird der Fehler 6 uncaught_exception in den LOG geschrieben:

host.UniFiController | 07.04.2021 13:11 | warn | Do   not restart adapter system.adapter.judoisoft.0 because restart loop detected
host.UniFiController | 07.04.2021 13:11 | info | Restart   adapter system.adapter.judoisoft.0 because enabled
host.UniFiController | 07.04.2021 13:11 | error | instance   system.adapter.judoisoft.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
judoisoft.0 | 07.04.2021 13:11 | info | (9450)   starting. Version 1.0.5 in /opt/iobroker/node_modules/iobroker.judoisoft,   node: v10.24.0, js-controller: 3.2.16
host.UniFiController | 07.04.2021 13:11 | info | instance   system.adapter.judoisoft.0 started with pid 9450
host.UniFiController | 07.04.2021 13:11 | info | Restart   adapter system.adapter.judoisoft.0 because enabled
host.UniFiController | 07.04.2021 13:11 | error | instance   system.adapter.judoisoft.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
judoisoft.0 | 07.04.2021 13:11 | info | (9432)   starting. Version 1.0.5 in /opt/iobroker/node_modules/iobroker.judoisoft,   node: v10.24.0, js-controller: 3.2.16
host.UniFiController | 07.04.2021 13:10 | info | instance   system.adapter.judoisoft.0 started with pid 9432
host.UniFiController | 07.04.2021 13:10 | info | Restart   adapter system.adapter.judoisoft.0 because enabled
host.UniFiController | 07.04.2021 13:10 | error | instance   system.adapter.judoisoft.0 terminated with code 6 (UNCAUGHT_EXCEPTION)
judoisoft.0 | 07.04.2021 13:10 | info | (9416)   starting. Version 1.0.5 in /opt/iobroker/node_modules/iobroker.judoisoft,   node: v10.24.0, js-controller: 3.2.16
host.UniFiController | 07.04.2021 12:10 | info | instance   system.adapter.judoisoft.0 started with pid 9416
host.UniFiController | 07.04.2021 12:10 | info | "system.adapter.judoisoft.0"   enabled

Vielen Dank schonmal für die Hilfe

VG
Felix

**Comment by arteck** [comment]
der Adapter läuft bei dir mehrmals..was nicht erlaubt ist..startre mal die Maschiene neu

**Comment by feuh** [comment]
ein neustart der Maschine brachte leider keine Besserung.

**Comment by arteck** [comment]
was hast du neu gestartet ?? ich meine die Maschiene wo dein iobroker läuft

**Comment by feuh** [comment]
Ja ich hab die Maschine, auf der der Broker läuft neu gestartet. Das Problem hat sich allerdings zwischenzeitlich dahingehend erledigt, dass ich die Maschine komplett neu aufsetzen musste und auch noch keine Zeit hatte den iobroker zu installieren und einzurichten
